import type { Metadata } from "next";
import "@styles/globals.css";
import localFont from "next/font/local";

const PlusJakartaSans = localFont({
  src: "../public/assets/fonts/PlusJakartaSans-VariableFont_wght.ttf",
});

export const metadata: Metadata = {
  title: "AxaCorp",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <meta name="theme-color" content="#fff" />
      </head>
      <body className={`${PlusJakartaSans.className}`}>{children}</body>
    </html>
  );
}
